-- 📝 Table for Logging AI Queries
CREATE TABLE IF NOT EXISTS query_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query TEXT NOT NULL,
    response_type TEXT, -- 'table', 'text', 'update', 'error'
    page_number INTEGER,
    timestamp TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE query_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON query_logs FOR SELECT USING (true);
CREATE POLICY "Allow service role insert" ON query_logs FOR INSERT WITH CHECK (true);
