-- 📊 SQL Schema for Structured Table Storage

-- 1. Create the table for storing extracted tables
CREATE TABLE IF NOT EXISTS document_tables (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT REFERENCES documents(id) ON DELETE CASCADE,
    page_number INTEGER NOT NULL,
    table_index INTEGER NOT NULL, -- Index of table on the page (0, 1, 2...)
    table_data JSONB NOT NULL,    -- Detailed JSON structure (rows, columns, metadata)
    summary TEXT,                 -- (Optional) LLM-generated summary of the table
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create an index on document_id for fast retrieval
CREATE INDEX IF NOT EXISTS idx_document_tables_doc_id ON document_tables(document_id);

-- 3. Create a GIN index on table_data for fast JSON querying (Critical for Phase 3)
CREATE INDEX IF NOT EXISTS idx_document_tables_data ON document_tables USING gin (table_data);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE document_tables ENABLE ROW LEVEL SECURITY;

-- 5. Create a policy to allow public read access (adjust if needed)
CREATE POLICY "Allow public read access" ON document_tables FOR SELECT USING (true);

-- 6. Create a policy to allow service role write access
CREATE POLICY "Allow service role insert" ON document_tables FOR INSERT WITH CHECK (true);
