-- 📢 Table for Live RBI Updates
CREATE TABLE IF NOT EXISTS rbi_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    url TEXT,
    pdf_url TEXT,
    publish_date DATE,
    summary TEXT,
    document_id BIGINT REFERENCES documents(id) ON DELETE SET NULL, -- Link to RAG record if ingested
    inserted_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE rbi_updates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access" ON rbi_updates FOR SELECT USING (true);
CREATE POLICY "Allow service role insert" ON rbi_updates FOR INSERT WITH CHECK (true);
